let player0 = {
    id:"", 
    pointSystemId:"", 
    btnId:"", 
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"",
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:"",
}
let player1 = {
    id:"", 
    pointSystemId:"", 
    btnId:"", 
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
let player2 = {
    id:"", 
    pointSystemId:"", 
    btnId:"", 
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
let player3 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
let player4 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
let player5 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",
    className1: "player-bean",
    className2: "extra-bean",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
let player6 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
let player7 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
let player8 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
let player9 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
let player10 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "extra-bean",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
let player11 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
let player12 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
let player13 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "extra-bean",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
let player14 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
let player15 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
let player16 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
let player17 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}

let theSquad = [
  player0,
  player1, 
  player2, 
  player3, 
  player4, 
  player5, 
  player6, 
  player7, 
  player8, 
  player9, 
  player10, 
  player11, 
  player12, 
  player13, 
  player14, 
  player15,
  player16,
  player17
]

export default theSquad;