const player0 = {
    id:"", 
    pointSystemId:"", 
    btnId:"", 
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"",
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:"",
}
const player1 = {
    id:"", 
    pointSystemId:"", 
    btnId:"", 
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
const player2 = {
    id:"", 
    pointSystemId:"", 
    btnId:"", 
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
const player3 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
const player4 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
const player5 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",
    className1: "player-bean",
    className2: "extra-bean",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
const player6 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
const player7 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
const player8 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
const player9 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
const player10 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "extra-bean",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
const player11 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
const player12 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
const player13 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "extra-bean",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
const player14 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
const player15 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
const player16 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}
const player17 = {
    id:"", 
    pointSystemId:"", 
    btnId:"",  
    className1: "player-bean",
    className2: "player-bean-blank",
    className3: "",
    className4: "",
    name:"", 
    surname:"", 
    shirtNumber:"", 
    position:"", 
    club:"", 
    price:"",
    overallPoints:"",
    recentMatchdayPoints:""
}

const theSquad = [
  player0,
  player1, 
  player2, 
  player3, 
  player4, 
  player5, 
  player6, 
  player7, 
  player8, 
  player9, 
  player10, 
  player11, 
  player12, 
  player13, 
  player14, 
  player15,
  player16,
  player17
]

export default theSquad;
